trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Lint
  jobs:
  - job: flake8
    steps:
    - script: flake8 .

- stage: Tests
  dependsOn: Lint
  jobs:
  - job: pytest
    steps:
    - script: pytest -v