trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Lint
  displayName: "Flake8 Linting"
  jobs:
  - job: flake8
    steps:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.12'

    - script: |
        python -m pip install --upgrade pip
        pip install flake8
      displayName: "Install flake8"

    - script: |
        python -m flake8 .
      displayName: "Run flake8"

- stage: Test
  displayName: "Run Tests"
  jobs:
  - job: pytest
    steps:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.12'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest httpx
      displayName: "Install dependencies"

    - script: |
        python -m pytest -v
      displayName: "Run tests"
